local _, ns = ...
local E, C, M, L, P = ns.E, ns.C, ns.M, ns.L, ns.P
local MODULE = P:GetModule("Bars")

-- Lua
local _G = getfenv(0)

function MODULE.CleanUp()
	E:ForceHide(ActionBarDownButton)
	E:ForceHide(ActionBarUpButton)
	E:ForceHide(ArtifactWatchBar)
	E:ForceHide(HonorWatchBar)
	E:ForceHide(MainMenuBar)
	E:ForceHide(MainMenuBarArtFrame, true)
	E:ForceHide(MainMenuBarLeftEndCap)
	E:ForceHide(MainMenuBarPageNumber)
	E:ForceHide(MainMenuBarRightEndCap)
	E:ForceHide(MainMenuBarTexture0)
	E:ForceHide(MainMenuBarTexture1)
	E:ForceHide(MainMenuBarTexture2)
	E:ForceHide(MainMenuBarTexture3)
	E:ForceHide(MainMenuBarVehicleLeaveButton)
	E:ForceHide(MainMenuExpBar)
	E:ForceHide(MultiBarBottomLeft)
	E:ForceHide(MultiBarBottomRight)
	E:ForceHide(MultiBarLeft)
	E:ForceHide(MultiBarRight)
	E:ForceHide(MultiCastActionBarFrame)
	E:ForceHide(OverrideActionBar)
	E:ForceHide(PetActionBarFrame)
	E:ForceHide(PossessBarFrame)
	E:ForceHide(ReputationWatchBar)
	E:ForceHide(SlidingActionBarTexture0)
	E:ForceHide(SlidingActionBarTexture1)
	E:ForceHide(SpellFlyoutBackgroundEnd)
	E:ForceHide(SpellFlyoutHorizontalBackground)
	E:ForceHide(SpellFlyoutVerticalBackground)
	E:ForceHide(StanceBarFrame)
	E:ForceHide(StanceBarLeft)
	E:ForceHide(StanceBarMiddle)
	E:ForceHide(StanceBarRight)
end
